### ISSUE TITLE
Should this library log errors even when they're re-thrown?

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-onedrive-support#106]
In the past weeks, when working with this library, I noticed that a lot of errors are practically logged twice - once by this library, once by the consumer code using it. I'd suggest to either not log errors at all, or provide an option to the `OneDrive` constructor that allows me to suppress logging for errors that are re-thrown.

**Comment by tripodsan** [comment]
well, the context of the error is different. the library might throw something like `error while fetching drive item: 404`, but the consumer code might know more to the semantic, like `error fetching file XYZ`.

but yes....this is a _problem_. ideally, this should be solve be using a different child-logger with a different log-level
