### ISSUE TITLE
getDriveItemFromShareLink returns no details if link has format `/drives/...`

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-onedrive-support#123]
In OneDrive.getDriveItemFromShareLink:

https://github.com/adobe/helix-onedrive-support/blob/ce86668d97d6795c250438281a47f8d46e448872/src/OneDrive.js#L313-L317

if the link given starts with `/drives/...`, only very basic information is returned (`id` and `parentReference`), as opposed to when that link starts with `https://`.  I see no way to get more information on the item (e.g. its last modified date) in the former case.

I suggest to either retrieve the information before returning from `getDriveItemFromShareLink` or add an optional parameter (e.g. `fetchInfo = false`) that fills the missing information. That information is returned from: 
```
https://graph.microsoft.com/v1.0/drives/<drive-id>/items/<item-id>
```

This feature would particularly help in solving https://github.com/adobe/helix-data-embed/issues/233

**Comment by tripodsan** [comment]
this shortcut is to avoid an extra roundtrip if not needed. since the users of this api need to fetch the item anyways, they'll have all the information they need.

**Comment by dominique-pfister** [comment]
OneDrive.getDriveItem() works as suggested, API change not required.
