### ISSUE TITLE
Document how to generate client id, secret and refresh token

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-onedrive-support#15]
For theblog content importer, I want to use this module (see https://github.com/kptdobe/helix-theblog-importer/blob/master/src/handlers/OneDriveHandler.js) to upload new markdown file to OneDrive.
To develop and since the importer needs to "write" into OneDrive, I need to create what's necessary on the Azure side. But I could not find it by myself.
@tripodsan could you describe how to do that ? Thanks a lot.

**Comment by tripodsan** [comment]
- I suggest you register a new app in azure and give it the correct permissions.
- then, use an id-token approach, so you don't need to provide a client-secret, but let the user login to microsoft when using the importer (but the authentication support for it is missing in this lib yet...https://github.com/adobe/helix-onedrive-support/issues/16)
- alternatively, use a client secret approach, but then only users that know the client-secret can use the tool.

**Comment by kptdobe** [comment]
@tripodsan created https://github.com/adobe/helix-onedrive-cli to help managing the authentication.
