### ISSUE TITLE
Recursion in cache.add in OneDrive.js

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-onedrive-support#166]
From time to time, we observe a `RangeError - Maximum call stack size exceeded` in our service that uses this library, and  the stack trace looks as follows:
```
RangeError: Maximum call stack size exceeded
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
    at /var/task/index.js:6005:9
```

The indicated line points to the following piece of code: https://github.com/adobe/helix-onedrive-support/blob/6154206679ca229577057c5d0d96f23b2b970e0b/src/OneDrive.js#L98-L104
where line 102 corresponds to line 6005 in the web packed service.

An example of this error in epsagon: https://app.epsagon.com/functions/118435662149/us-east-1/helix-services--content-proxy?filters%5Bstatus%5D%5B0%5D=error

**Comment by tripodsan** [comment]
oh! I think this could happen if the adal cache is the global memory cache and the onedrive class is instantiated several times.
