### ISSUE TITLE
use sharepoint API to list and read files if possible

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-onedrive-support#217]
the sharepoint API is a gazillion times faster and seems to be more up-to-date than accessing onedrive via the msgraph api.
if a resource is on sharepoint, it's API should be used.

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest

**Note:** resolveShareLink
- should check if sharepoint url and sanitize
- if not, use drive id

**Comment by davidnuescheler** [comment]
LOL 👍

**Comment by tripodsan** [comment]
@dominique-pfister can you take a look at this?
