### ISSUE TITLE
Make authenticate method less confusing

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-onedrive-support#321]
the authenticate method uses whatever credentials are passed in the constructor to choose the correct authentication method.
this is a problem when for example the token refresh of an cached refreshtoken fails, and then a different auth succeeds with the wrong credentials.

the main problem is with the `acquireTokenByClientCredential` which is rarely used. when using it to login, it will also cache the access-token in the (persisted) token cache, so the access token can be reused. so it must be possible to fall through the silent login but then still get a new token via acquireTokenByClientCredential.

otoh, when a cache-based only login is required (eg with a stored account), it should never authenticate with acquireTokenByClientCredential.  

possible solutions:
- can different methods for different auths. the problem is then the auto-authenticate via `doFetch()`
- define the auth-method via field/constructor param

**Comment by dominique-pfister** [comment]
> define the auth-method via field/constructor param
👍 

what about an additional constructor parameter:
```
   acquireMethods = one or many of ['silent','byClientCredential', 'byDeviceCode']
```
and default is [`silent`] ?

**Comment by dominique-pfister** [comment]
Fixed by passing `acquireMethod` explicitly
