### ISSUE TITLE
request is deprecated; replace with helix-fetch

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-onedrive-support#60]
[request](https://github.com/request/request) is deprecated and should be replaced.
best candidate is [helix-fetch](https://github.com/adobe/helix-fetch)

**Comment by stefan-guggisberg** [comment]
To make matters worse: `helix-onedrive-support` is not only using [request](https://github.com/request/request) internally, it also exposes the deprecated proprietary API via `OneDrive.getClient()`.
